services:
  server:
    container_name: kaluste_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=${MONGODB_URI}
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kaluste-frontend
    environment:
      VITE_BACKEND_URL: http://localhost:8080/api
    depends_on:
      - server
  nginx:
    image: nginx:latest
    container_name: kaluste_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - app
