services:
  app:
    image: todo-frontend
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    environment:
      VITE_BACKEND_URL: http://localhost:8080/api
  server:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      MONGO_URI: mongodb://the_username:the_password@mongo:27017/the_database?authSource=the_database
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - server
volumes:
  mongo_data:
  redis_data:
